camunda.bpm.metrics.enabled=false
camunda.bpm.admin-user.id=demo
camunda.bpm.admin-user.password=demo
camunda.bpm.admin-user.first-name=demo
server.port=8082

# Participant scenario configuration (university, farm, emergency, rental)
# app.scenario=university